name: Version develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' 
    steps:
       # Tag
      - name: Tag creation
        uses: phish108/autotag-action@1.1.37
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          release-branch: "master,main,develop"
        id: version